    name: Publish to PyPI

    on:
      release:
        types: [published]

    jobs:
      deploy:
        runs-on: ubuntu-latest
        permissions:
          id-token: write # Required for trusted publishing
        steps:
          - uses: actions/checkout@v5

          - name: Install management tools
            uses: astral-sh/setup-uv@v5
            with:
                version: "0.8.4"

          - name: Install dependencies
            run: uv sync

          - name: Build package
            run: uv build

          - name: Publish package to PyPI
            uses: pypa/gh-action-pypi-publish@release/v1